name: Build HoTok Plugin
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Theos and iOS SDK
        uses: rowsandcolumns/theos-action@v1
        with:
          theos-version: 'master'

      - name: Create Makefile
        run: |
          echo "TARGET = iphone:clang:latest:14.0" > Makefile
          echo "ARCHS = arm64" >> Makefile
          echo "include \$(THEOS)/makefiles/common.mk" >> Makefile
          echo "TWEAK_NAME = HoTokChanger" >> Makefile
          echo "HoTokChanger_FILES = Tweak.x" >> Makefile
          echo "HoTokChanger_CFLAGS = -fobjc-arc" >> Makefile
          echo "include \$(THEOS)/makefiles/tweak.mk" >> Makefile

      - name: Compile Dylib
        run: |
          make package GO_EASY=1 FINALPACKAGE=1
          mv .theos/obj/HoTokChanger.dylib ./HoTokChanger.dylib

      - name: Upload Finished File
        uses: actions/upload-artifact@v4
        with:
          name: HoTokChanger-Plugin
          path: ./HoTokChanger.dylib
