name: Build HoTok Plugin
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tools and Theos
        run: |
          # Устанавливаем нужные для компиляции библиотеки на Linux
          sudo apt-get update
          sudo apt-get install -y clang make perl git xz-utils
          
          # Скачиваем оригинальный Theos в домашнюю папку
          git clone --recursive https://github.com ~/theos
          
          # Скачиваем официальный iOS SDK
          curl -LO https://github.com
          tar -xf iPhoneOS14.5.sdk.tar.xz -C ~/theos/sdks/
          rm iPhoneOS14.5.sdk.tar.xz

      - name: Create Makefile
        run: |
          echo "TARGET = iphone:clang:latest:14.0" > Makefile
          echo "ARCHS = arm64" >> Makefile
          echo "include \$(THEOS)/makefiles/common.mk" >> Makefile
          echo "TWEAK_NAME = HoTokChanger" >> Makefile
          echo "HoTokChanger_FILES = Tweak.x" >> Makefile
          echo "HoTokChanger_CFLAGS = -fobjc-arc" >> Makefile
          echo "include \$(THEOS)/makefiles/tweak.mk" >> Makefile

      - name: Compile Dylib
        run: |
          # Указываем компилятору, где искать Theos
          export THEOS=~/theos
          make package GO_EASY=1 FINALPACKAGE=1
          mv .theos/obj/HoTokChanger.dylib ./HoTokChanger.dylib

      - name: Upload Finished File
        uses: actions/upload-artifact@v4
        with:
          name: HoTokChanger-Plugin
          path: ./HoTokChanger.dylib
